### ISSUE TITLE
$authenticationState never changes since new release

### ISSUE THREAD

**Issue by christiangoudreau** [okta/okta-angular#10]
After upating to the new release, authTokenManager is stuck on state pending after login with the okta login widget. I have to refresh the browser to get isAuthenticated = true and I'm using the OktaCallbackComponent. 

Subscribing on authTokenManager directly instead of $authenticationState doesn't work either.

I'm using okta widget 4.5.2

Thanks,

**Comment by aarongranick-okta** [comment]
@christiangoudreau Thanks for the submission. We will look into this right away.

Internal ref: OKTA-344860

**Comment by aarongranick-okta** [comment]
@christiangoudreau Just want to clarify: - 

It sounds like you are using an embedded widget and doing a login redirect flow. Is this correct? 
Can you share the code of your "signin" component which is using the widget?

**Comment by christiangoudreau** [comment]
Yes it is correct, here it is :
```
    ngOnInit(): void {
        this.oktaSignIn.renderEl({ el: '#okta-login-container' }, (response: any) => {
             // Nothing important
        });
    }
```

After successfully login in, we are redirected to this component by OktaCallbackComponent. It essentially show a loading animation until this.isAuthenticated is true. But when redirected after login the status is pending and isAuthenticated returns false. I have to refresh to have my isAuthenticated = true.
```
    ngOnInit(): void {
        combineLatest([this.globalSelector.appTitle$(), this.translateService.onLangChange])
            .pipe(mergeMap(([titleKey, _]) => this.translateService.get(titleKey)))
            .subscribe(title => this.titleService.setTitle(`${ APP_NAME } - ${ title }`));

        this.globalSelector.isLoading().subscribe(isLoading => this.isLoading = isLoading);

        this.oktaAuth.$authenticationState.subscribe(isAuthenticated => {
            this.isAuthenticated = isAuthenticated;

            // If the user is authenticated, we start the initialization of the app.
            this.isAuthenticated && this.store$.dispatch(new Initialize());
        });
    }
```

Thanks and best regards,

**Comment by aarongranick-okta** [comment]
@christiangoudreau I have been able to reproduce the problem in one of our samples. I believe the problem is related to timing. Before the callback component redirects to your component, the tokens are stored and the internal auth state is updated, so `isAuthenticated` is true. This happens before `subscribe` is called on the `$authenticationState` Observable. One problem with Observables is that they can only notify you of updates in the **future** and cannot tell you the current value.

Try this code in your component:

```

        // Check current value
        this.isAuthenticated = await this.oktAuth.isAuthenticated();
        if (this.isAuthenticated) {
            this.store$.dispatch(new Initialize());
        } else {
       // Subscribe to changes
        this.oktaAuth.$authenticationState.subscribe(isAuthenticated => {
            this.isAuthenticated = isAuthenticated;

            // If the user is authenticated, we start the initialization of the app.
            this.isAuthenticated && this.store$.dispatch(new Initialize());
        });
    }
```

I have created an issue to investigate using a `BehaviorSubject` instead of an `Observable` within the SDK. The `BehaviorSubject` would fire the current value immediately on `subscribe`. If we make this change it would come in the next major release.

**Comment by christiangoudreau** [comment]
That would be great. I did have something similar to what you have at first with : this.isAuthenticated = await this.oktAuth.isAuthenticated(); and then subscribing to changes. But the observable nerver send future updates.

**Comment by jraadt** [comment]
This is what I'm doing to detect when the user is authenticated:

```
merge(from(this. oktAuth.isAuthenticated()), this. oktAuth.$authenticationState)
      .pipe(first(isAuthenticated => isAuthenticated))
      .subscribe(() => console.log('You are authenticated!'));
```

**Comment by sbuscher** [comment]
@aarongranick-okta take a look at the [BehaviorSubject](https://rxjs-dev.firebaseapp.com/guide/subject#behaviorsubject) observable which emits the last known value to new subscribers. Changing $authenticationState to use a BehaviorSubject would be a good approach to resolve the issue. 

```
authenticationStateSubject = new BehaviorSubject<boolean>(false);  // must initialize value
$authenticationState = authenticationStateSubject.AsObservable();
```

**Comment by aarongranick-okta** [comment]
@sbuscher Thanks! we have this planned for the next major version release.

**Comment by shuowu** [comment]
@christiangoudreau I think the cause of no authState update is due to no explicit calls have been triggered to update the authState once login success in the widget. 

Can you follow the [custom login sample](https://github.com/okta/samples-js-angular/blob/master/custom-login/src/app/login/login.component.ts#L65) to call the [handleLoginRedirect](https://github.com/okta/okta-auth-js#handleloginredirecttokens) in the widget success callback. You should be able to get an updated authState from the observable afterward.

**Comment by christiangoudreau** [comment]
That did the trick. Thanks for pointing that out to me!
