### ISSUE TITLE
AuthApiError while login with Angular 10 and Okta v3

### ISSUE THREAD

**Issue by MonuGoyath** [okta/okta-angular#14]
After upgrading to v3, I get the 401 error from `/token` endpoint. When gone through documentation - found out the problem is "invalid_client: The specified client_id wasn't found.".

But the same whole setup works with v1.2.2, while I get the error for v3.0.1.

First I enter credentials and then it gets redirect to '/implicit/callback' route and there is OktaCallbackComponent to deal.

Finally I get the empty screen with text - **AuthApiError** & below is the error message in console

**Endpoint** - https://******.okta.com/oauth2/v1/token
**Response** - {"error":"invalid_client","error_description":"Client authentication failed. Either the client or the client credentials are invalid."}

Is there any problem with the Angular 10 & Okta v3 combination or is there any fault with client_id?

FYI - my setup is

- Allowed Grant Types -> Authorization Code & Implicit(Hybrid)
- Login Flow -> Redirect to app to initiate login(OIDC Compliant)

Okta Configuration in Angular

- issuer: 'https://{domain}.okta.com/' & 'https://{}.com/oauth2/default' (tried both)
- redirectUri: 'https://***.com/implicit/callback'
- clientId: '***'

**Comment by swiftone** [comment]
@MonuGoyath - Thanks for the report.  Can you confirm that your app is a "spa" type in the Okta admin console, rather than a "Web" type?   We've had reports similar to yours where that was the source of the problem. 

If you do have a web type, you might be able to fix the problem by passing `pkce: false` in your config, but that is a bit of a hack.  The better response is to use a client_id that is of "spa" type, as okta-angular isn't intended to support "web" types.  

If that isn't the case please let us know and we can dig deeper.

**Comment by MonuGoyath** [comment]
@swiftone , Thanks for your quick response.

Yeah my app is of type Web & when i tried with disabling pkce - it works fine.

But, do I need to be concerned as I couldn't change the type of app & I would like to go ahead with Web type(will there be any problem in future with app type of Web)?

**Comment by swiftone** [comment]
My recommendation would be to change to app type of SPA - while I'm not aware of any current expected problems with what you are doing outside of the PKCE flow, this is basically undefined behavior.  I cannot promise anything about the future.

**Comment by swiftone** [comment]
Closing issue as resolved - if problems reappear, feel free to reopen or create a new issue and reference this one.
