### ISSUE TITLE
OktaSignIn helpLinks customization not working as expected

### ISSUE THREAD

**Issue by alsoicode** [okta/okta-angular#16]
Hello,

When specifying a `forgotPassword` custom URL according to: https://developer.okta.com/docs/guides/style-the-widget/style-self-hosted/

```
this.widget = new OktaSignIn({
  ...,
  helpLinks: {
    forgotPassword: 'https://www.labcorplink.com/ui/#/credentials/forgotpassword'
  },
});
```

The resulting URL upon inspection is simply: `#`. What am I doing wrong?

**Comment by shuowu** [comment]
@alsoicode Your config should work, based on the widget implementation, it looks like the redirection is handled by the `click` event instead of injecting the URL in the dom. 

here is the implementation if you are interested: https://github.com/okta/okta-signin-widget/blob/master/src/views/shared/Footer.js#L89
