### ISSUE TITLE
 There is no typings path for RouterOutlet in ../node_modules/@okta/okta-angular/bundles/okta-angular.umd.js

### ISSUE THREAD

**Issue by vigneshshankaradevan** [okta/okta-angular#27]
Steps to reproduce: 
1. ng new OktaSample 
2. cd OktaSample
3. npm install --save @okta/okta-angular 
4. in package.json 
    `"scripts": { 
                  "test": "ngcc --properties main && ng test" ` 
5. npm ci 
6. npm run test

Detail Error : 

Error: Error on worker #2: Error: There is no typings path for RouterOutlet in  ../angular-test/OktaSample/node_modules/@okta/okta-angular/bundles/okta-angular.umd.js.
We need to add an export for this class to a .d.ts typings file because Angular compiler needs to be able to reference this class in compiled code, such as templates.
The simplest fix for this is to ensure that this class is exported from the package's entry-point.

Angular version 

`"@angular/core": "~11.0.5"
"@angular/cli": "~11.0.5"`

 `npm -v :  6.14.8 `

` node -v :  v14.15.1` 

Log file : 
[2021-03-03T14_46_48_719Z-debug.log](https://github.com/okta/okta-angular/files/6076732/2021-03-03T14_46_48_719Z-debug.log)

**Comment by swiftone** [comment]
@vigneshshankaradevan - Thanks for the report, I'll pass this by one of our Angular folks.  I'm not clear that this isn't something you would need to add - okta-angular is a toolkit to write your applications, not an application, and thus doesn't populate RouterOutlet, but as I said, my Angular knowledge is very limited and I'll check with the team.

**Comment by aarongranick-okta** [comment]
@vigneshshankaradevan The `RouterOutlet` type is not owned by `okta-auth-js`, it is part of angular: https://angular.io/api/router/RouterOutlet

You may need to add the angular types to your project: https://www.npmjs.com/package/@types/angular

**Comment by atotalnoob** [comment]
@swiftone But you have a callback component that your docs say to mount on a router https://github.com/okta/okta-angular#oktacallbackcomponent

Which means it will be put into a `RouterOutlet` and cause this error. 

We also tried `ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points && ng test`

**Comment by swiftone** [comment]
> Which means it will be put into a RouterOutlet and cause this error

The key part there being "Will be put into a RouterOutlet".  "will be", not "are". You have to do the step of mapping them to a router.  The types for the callback component should be provided for you to use when you do so.

The reproduction steps you've listed have not created a working application, even if the error you are seeing didn't happen, and the error you are seeing is because the application isn't complete.

We have a guide here that shows the steps to create an application using okta-angular: https://developer.okta.com/docs/guides/sign-into-spa/angular/before-you-begin/ (note it is a few pages, and on a later page you can see where the Router information is set up: https://developer.okta.com/docs/guides/sign-into-spa/angular/define-callback/ )

Alternatively, you can download a sample application built using this SDK here: 
https://github.com/okta/samples-js-angular

Please build a minimal application and you should see this particular issue is not a concern.

Hope that helps!

**Comment by atotalnoob** [comment]
Having the credentials there are pointless, since it does not matter since it **cannot build**. We have an application with these details properly populated. 

Use the below zipped reproducer and run `npm ci && npm run test`
[okta-reproducer.zip](https://github.com/okta/okta-angular/files/6078198/okta-reproducer.zip)

**Comment by swiftone** [comment]
I'm not sure what you mean about "credentials", since I was talking about the Router configuration.

However, running your code I can see the same error.  I don't know what it refers to, since, as pointed out above, `RouterOutlet` is not ours.

I'll file a ticket for the team to take a look, this is the first such error we've had reported.

**Comment by swiftone** [comment]
Internal Ref: OKTA-375466

**Comment by vigneshshankaradevan** [comment]
I have updated npm to 7.6.0 (`npm i -g npm@7.6.0`) and  replaced `"test": "ngcc --properties main && ng test"` with  `"ngcc --properties es2015 browser module main && ng test"`   now everything worked fine for me

**Comment by swiftone** [comment]
Great, glad it worked out, thanks for the update.

**Comment by atotalnoob** [comment]
There is still an issue, we just figured out a workaround... 

We clearly demonstrated a bug.
